version: "2"
formatters:
  enable:
    - gci
linters:
  default: all
  disable:
    - exhaustruct
    - nestif
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - testpackage
    - wsl
    - wsl_v5
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
          - err113
          - varnamelen
          - lll
      - path: examples/
        linters:
          - revive
          - mnd
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - '**/*.go'
            - '!$test'
            - '!**/flag/binding/*.go'
            - '!**/examples/viper/*.go'
          allow:
            - $gostd
            - github.com/spf13/cobra$
            - github.com/spf13/pflag$
            - github.com/neiser/go-nagini/command$
            - github.com/neiser/go-nagini/flag$
        binding:
          list-mode: strict
          files:
            - '!$test'
            - '**/flag/binding/*.go'
            - '**/examples/viper/*.go'
          allow:
            - $gostd
            - github.com/spf13/cobra$
            - github.com/spf13/pflag$
            - github.com/spf13/viper$
            - github.com/neiser/go-nagini/command$
            - github.com/neiser/go-nagini/flag$
            - github.com/neiser/go-nagini/flag/binding$
    ireturn:
      allow:
        - pflag.Value$
        - flag.Slice$
        - error
        - generic
