name: Update Readme
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  embed-code:
    name: Embed code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert tabs to spaces for README
        run: find examples -type f -name "*.go" -exec sed -i 's/\t/  /g' {} +

      - uses: kvankova/code-embedder@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
